# Copyright (c) Christopher Di Bella.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
task:
  container:
    dockerfile: config/ci/Dockerfile
    cpu: 2
    memory: 2G
  env:
    PROFILE: ${HOME}/.conan/profiles/default
    matrix:
      - COMPILER: gcc-9
      - COMPILER: clang-9-libstdcxx
      - COMPILER: clang-9-libcxx
    matrix:
      - BUILD_TYPE: Debug
      - BUILD_TYPE: Release
  pre_conan_install_script:
    - conan config install config/conan
  conan_install_script:
    - mkdir -p build-${COMPILER}-${BUILD_TYPE}
    - cd build-${COMPILER}-${BUILD_TYPE}
    - conan install .. --profile=${COMPILER} --settings build_type=${BUILD_TYPE}
  conan_build_configure_script:
    - cd build-${COMPILER}-${BUILD_TYPE}
    - conan build .. --configure
  build_script:
    - cd build-${COMPILER}-${BUILD_TYPE}
    - ninja -v
  test_script:
    - cd build-${COMPILER}-${BUILD_TYPE}
    - conan build .. --test
